# Generated by Django 5.2.8 on 2025-11-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату (Stripe Checkout)"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "ожидает оплаты"),
                    ("paid", "оплачен"),
                    ("canceled", "отменён"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID цены в Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID продукта в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID сессии Checkout в Stripe",
            ),
        ),
    ]
