# Generated by Django 5.2.8 on 2025-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_url_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату (Stripe Checkout)",
            ),
        ),
    ]
