# Generated by Django 5.2.8 on 2025-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1000, max_digits=10, verbose_name="цена"
            ),
        ),
    ]
